export const peliculasPorDefecto = [
    {
      id: crypto.randomUUID(),
      titulo: "The Matrix",
      genero: "Ciencia ficción",
      tipo: "Película",
      año: "1999",
      director: "Lana y Lilly Wachowski",
      rating: 5,
      vista: true,
    },
    {
      id: crypto.randomUUID(),
      titulo: "Breaking Bad",
      genero: "Drama",
      tipo: "Serie",
      año: "2008",
      director: "Vince Gilligan",
      rating: 5,
      vista: false,
    },
    {
        id: crypto.randomUUID(),
        titulo: "Breaking Bad",
        genero: "Drama",
        tipo: "Serie",
        año: "2008",
        director: "Vince Gilligan",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Breaking Bad",
        genero: "Drama",
        tipo: "Serie",
        año: "2008",
        director: "Vince Gilligan",
        rating: 5,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Breaking Bad",
        genero: "Drama",
        tipo: "Serie",
        año: "2008",
        director: "Vince Gilligan",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Breaking Bad",
        genero: "Drama",
        tipo: "Serie",
        año: "2008",
        director: "Vince Gilligan",
        rating: 5,
        vista: true,
      }
  ];
