export const peliculasPorDefecto = [
    {
      id: crypto.randomUUID(),
      titulo: "The Matrix",
      genero: "Ciencia ficción",
      tipo: "Película",
      año: "1999",
      director: "Lana y Lilly Wachowski",
      rating: 5,
      vista: true,
    },
    {
      id: crypto.randomUUID(),
      titulo: "Breaking Bad",
      genero: "Drama",
      tipo: "Serie",
      año: "2008",
      director: "Vince Gilligan",
      rating: 5,
      vista: false,
    },
    {
        id: crypto.randomUUID(),
        titulo: "Better Call Saul",
        genero: "Drama",
        tipo: "Serie",
        año: "2018",
        director: "Vince Gilligan",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "The Sopranos",
        genero: "Drama",
        tipo: "Serie",
        año: "2008",
        director: "Julio Cesar",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Los Simpson",
        genero: "Comedia",
        tipo: "Serie",
        año: "1995",
        director: "David Grhole",
        rating: 5,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Ted Lasso",
        genero: "Comedia",
        tipo: "Serie",
        año: "2019",
        director: "Cesar Navarro",
        rating: 5,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Coco",
        genero: "Comedia",
        tipo: "Pelicula",
        año: "2019",
        director: "Disney",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "The Joker",
        genero: "Drama",
        tipo: "Pelicula",
        año: "2019",
        director: "Todd Philips",
        rating: 5,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Bring her back",
        genero: "Terror",
        tipo: "Pelicula",
        año: "2022",
        director: "Jorge Thomas",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Talk To Me",
        genero: "Terror",
        tipo: "Pelicula",
        año: "2024",
        director: "Fernando Torres",
        rating: 5,
        vista: false,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Parasite",
        genero: "Drama",
        tipo: "Pelicula",
        año: "2019",
        director: "Bong Joo Park",
        rating: 5,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "Violeta",
        genero: "Comedia",
        tipo: "Serie",
        año: "2008",
        director: "Guillermo Fernando",
        rating: 2,
        vista: true,
      },
      {
        id: crypto.randomUUID(),
        titulo: "The Bear",
        genero: "Drama",
        tipo: "Serie",
        año: "2023",
        director: "Francisco The Pope",
        rating: 5,
        vista: true,
      },      {
        id: crypto.randomUUID(),
        titulo: "The Mansion",
        genero: "Romance",
        tipo: "Serie",
        año: "2008",
        director: "Paloma Hernandez",
        rating: 5,
        vista: true,
      }
  ];
